### ISSUE TITLE
Allow users to update the filter and group columns via a UI element

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#102]

**Comment by jwildfire** [comment]
This is another custom control. We should create a quick wireframe first before implementing.

**Comment by emmorris** [comment]
Add a float right gear icon for settings.

**Comment by brittsikora** [comment]
Expected outcome: User can update filters and group variables using the ui

Result: Pass

![110a](https://user-images.githubusercontent.com/14914918/27449118-444c7db6-5755-11e7-80e7-c1b65c02080e.JPG)
![110b](https://user-images.githubusercontent.com/14914918/27449120-45a304dc-5755-11e7-9dce-22489a47c58a.JPG)
