### ISSUE TITLE
Fix bug - numeric data filters behave as character filters

### ISSUE THREAD

**Issue by bzkrouse** [RhoInc/web-codebook#104]
This is a bug that appears w/ the R implementation for variables that are numeric in nature.  The initial chart renders fine, but filters do not work - any selection will cause the chart to clear w/ message that no data exists under the current selections. Here is the code that made a temporary fix:

        data.forEach(function(row){
            var cols = Object.keys(row)
            cols.forEach(function(col){
              row[col] = ""+row[col]
            })
        })

**Comment by jwildfire** [comment]
@bzkrouse - I've already forgotten the details about this. Could your provide some detail in the issue description and (if possible) settings/data to reproduce the bug. 

Once that is in we can decide whether to add this to v1.1

**Comment by bzkrouse** [comment]
@jwildfire - see if the description above is sufficient?

**Comment by jwildfire** [comment]
@bzkrouse: Perfect - Thanks. 

Adding to 1.1 - the (slightly hack-y) solution that we've used elsewhere is just to coerce everything to character on the initial data load. It should work fine here.

**Comment by emmorris** [comment]
Jeremy and Spencer have both confirmed that this is working as expected, so no additional manual testing needed.
