### ISSUE TITLE
Move Charts/Listing Toggle from Controls Div to a new Nav Div

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#105]
Put a simple nav with 2 tabs directly above the controls.

**Comment by jwildfire** [comment]
This is mostly done using the model from [safety-explorer-suite](https://github.com/RhoInc/safety-explorer-suite/tree/master/src/explorer/nav). Relevant new settings are `settings.tabs` and `settings.defaultTab` which are [described in the wiki](https://github.com/RhoInc/web-codebook/wiki/Codebook-Configuration#settingstabs).

**Comment by emmorris** [comment]
Test Notes: Test settings in the wiki using this format:
{"tabs":["codebook","settings"],"defaultTab":"settings"}

**Comment by brittsikora** [comment]
Expected outcome: Adding the tab settings from the wiki will modify the chart to yield new tabs and/or default tabs

Result: Pass

![105](https://user-images.githubusercontent.com/14914918/27438266-aa991f7a-5732-11e7-86e0-4c784e63c7eb.JPG)
