### ISSUE TITLE
Show/Hide all charts buttons should be hidden when viewing listing. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#109]

**Comment by jroden** [comment]
^Also hide when viewing Settings?

**Comment by jwildfire** [comment]
Rethinking implementation. See #146. This should be done in conjunction with those updates.

**Comment by jwildfire** [comment]
Test Notes: Confirm that show/hide buttons are in header for the codebook section instead of the controls area, and that they work as expected. 

<img width="1044" alt="screen shot 2017-08-01 at 12 19 10 pm" src="https://user-images.githubusercontent.com/3680095/28842830-07c277d2-76b4-11e7-8a3b-87ae313c0ea2.png">

**Comment by brittsikora** [comment]
Pass

![109a](https://user-images.githubusercontent.com/14914918/28845672-ceee6556-76d6-11e7-97e0-221811a290ba.JPG)

![109b](https://user-images.githubusercontent.com/14914918/28845677-d01b8260-76d6-11e7-9353-c9daaaa4743c.JPG)
