### ISSUE TITLE
Automatically hide Nav when it has less than 2 items

### ISSUE THREAD

**Issue by emmorris** [RhoInc/web-codebook#122]
Add reasonable default logic (if only one item then hide)

**Comment by jroden** [comment]
Just to verify- the only change in this functionality is:
1. If the settings "tabs" field only has one tab listed (from codebook, listing, settings) then hide the nav menu

**Comment by jwildfire** [comment]
Test Notes: Confirm that no nav appears with settings = `{"tabs":["codebook"]}`

**Comment by brittsikora** [comment]
Pass

![122](https://user-images.githubusercontent.com/14914918/28846228-a4c700d8-76d8-11e7-90fb-8eb5ef030b90.JPG)
