### ISSUE TITLE
Allow users to update labels from settings screen

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#126]

**Comment by samussiah** [comment]
Test Notes: This change allows users to define variable labels from the settings tab.  Entering a label in the _Label_ column updates the variable rows in the codebook view and adds tooltips to column headers in the data listing. 

Confirm the following functionality:
- Entering a value in a text box in the _Label_ column on the settings tab updates the variable names in the codebook.
- Entering a value in a text box in the _Label_ column on the settings tab updates the tooltips in the data listing.
- Entering a value in a text box in the _Label_ column on the settings tab for group variables updates the Group by options (**I think we dropped this functionality but just in case I though I'd mention it in case we wanted to bring it back**).
- Entering a value in a text box in the _Label_ column on the settings tab for filter variables adds a description underneath the respective filter (**I think we dropped this functionality but just in case I though I'd mention it in case we wanted to bring it back**).

_To effect a label focus must leave the text box by pressing enter or tab or clicking outside the text box._

**Comment by jwildfire** [comment]
I think we can ignore the 3rd and 4th bullets in test notes above. Let's create a separate issue for that functionality and consider adding it in a future release.

**Comment by brittsikora** [comment]
Pass

Add labels
![126a](https://user-images.githubusercontent.com/14914918/29190172-1ce650e0-7de7-11e7-9c31-ee406b47699b.JPG)

View labels in codebook
![126b](https://user-images.githubusercontent.com/14914918/29190200-364b39e2-7de7-11e7-99ea-866ea4a51792.JPG)

View labels as tooltips
![126c](https://user-images.githubusercontent.com/14914918/29190196-323e2e0e-7de7-11e7-930d-145e6024bbb5.png)
