### ISSUE TITLE
Controls container not scaling to Show/Hide controls element when controls are hidden.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#132]
![image](https://user-images.githubusercontent.com/5428548/27738900-d73dd36a-5d7a-11e7-9e6f-c56f6a0cfb96.png)

**Comment by jwildfire** [comment]
Relevant css: 
```
.web-codebook .controls.minimized {
  height:28px;
}
```

Looks ok for me now. Maybe other css tweaks fixed the issue?

**Comment by jwildfire** [comment]
Test Notes: Confirm that the "Show" button is fully in the div in various browsers.

**Comment by brittsikora** [comment]
Used commit: 2f5e17f090ccfea6548bce5dc965f814bc270878

This still looks wonky in all browsers
![132](https://user-images.githubusercontent.com/14914918/28944979-9dcf63d8-7872-11e7-96de-38581028bf9b.JPG)

**Comment by brittsikora** [comment]
Pass

Tested using commit: 223db2b6e6039729e90e9699bbaef02375981cd3

![132a](https://user-images.githubusercontent.com/14914918/28978692-f3300b00-7914-11e7-8c72-f85dcd4c9af3.JPG)
