### ISSUE TITLE
Horizontal bar charts do not display mean comparison line

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/web-codebook#135]
This was just happening in IE when I was testing it, but when I went to recreate it, none of the browsers would show this

Current view:
![135](https://user-images.githubusercontent.com/14914918/27752722-7b6e24aa-5db0-11e7-86ff-d45ef211e3d1.png)

**Comment by samussiah** [comment]
Those horizontal difference lines should only appear in grouped horizontal bar charts summarized by rate.

**Comment by brittsikora** [comment]
Gotcha, I just confirmed that it works. Thanks for clarifying
