### ISSUE TITLE
Hidden variables show up in group/filter list via the settings screen.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#138]

**Comment by brittsikora** [comment]
Hey Spencer, how do you want me to test this?

**Comment by samussiah** [comment]
go to the settings screen, hide a variable, then set it as a group and/or filter.

**Comment by brittsikora** [comment]
Expected Outcome: When a user hides a variable, it cannot be set as a group and/or filter

Result: Pass
