### ISSUE TITLE
Math.cbrt() not supported in IE

### ISSUE THREAD

**Issue by emmorris** [RhoInc/web-codebook#14]

**Comment by jwildfire** [comment]
This appears to be an issue with cube root not being supported in older browsers

**Comment by jwildfire** [comment]
Looks like `Math.pow(a,(1.0/3.0))` will work in all browsers, so going to change to that [ref](http://stackoverflow.com/questions/24227017/difference-in-math-cbrt-and-math-pow)

**Comment by jwildfire** [comment]
Test Notes: Just confirm that everything renders as expected in IE and Firefox for dev-v1.0.0

**Comment by brittsikora** [comment]
Expected Result: Opened Codebook in Firefox and IE, all functionality works as expected

Outcome: Pass
