### ISSUE TITLE
Add highlight functionality to data listing

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#142]
After #97, do the following: 
1. Add a highlighed class to all listing rows matching a row in `codebook.data.highlighted`
   - consider a simple css rule that just adds a yellow background
2. Sort the table to show the highlighted values first by default. (User can override this order by clicking the headers.)
3. Update the `codebook.controls.highlight.clear` method to remove highlight class and note from details page.

Should be pretty straightforward to add this via 2 new methods - something like: `codebook.dataListing.functionality.addHighlight()` and `removeHighlight()`

**Comment by jwildfire** [comment]
Test Notes: See [here](https://github.com/RhoInc/web-codebook/issues/97#issuecomment-319479478)

**Comment by brittsikora** [comment]
Pass

![97b](https://user-images.githubusercontent.com/14914918/28846412-53b5ead2-76d9-11e7-9a0a-4e4d09576ada.JPG)

![97c](https://user-images.githubusercontent.com/14914918/28846414-5628203c-76d9-11e7-9563-551dd10b2011.JPG)
