### ISSUE TITLE
Allow users to highlight multiple marks

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#143]
Complete after #97. Consider using brush events instead of click events to facilitate highlighting multiple marks. Alternatively, we could allow ctrl-click events to toggle marks.

**Comment by samussiah** [comment]
Going with click one -> highlight, click twice -> remove highlight.  Brushing isn't really necessary nor trivial because it kind of messes up our click listeners.

**Comment by jwildfire** [comment]
Agree with click the approach.

**Comment by jwildfire** [comment]
Test Notes: This change allows multiple bars to be highlighted. Clicking a bar no longer resets all highlights as described in the test notes for #97. 

Confirm the following functionality for the 6 use cases listed in #97:
- Clicking a bar with no highlighted values, adds the values to the highlighted population.
- Clicking a bar with any highlighted values, removes all of those values from the highlighted population. 
- Confirm that this functionality works across multiple chart types. That is, you can add highlights by clicking on a bar Chart A, and then remove those highlights by clicking on a bar in Chart B.

**Comment by samussiah** [comment]
Minor modification: clicking a gray bar adds records; clicking an orange bar removes records.

**Comment by brittsikora** [comment]
Pass

Tested with commit: 98deeff04113155cc426265aa412f2d231019ee8

Histogram, grouped
![143_histogram_grouped](https://user-images.githubusercontent.com/14914918/28944754-b49389ce-7871-11e7-8379-52cbb17e0528.JPG)

Histogram, ungrouped
![143_histogram_ungrouped](https://user-images.githubusercontent.com/14914918/28944605-39885ae8-7871-11e7-98c6-9913509dbc15.JPG)

Vertical bar chart, grouped
![143_vertical_grouped](https://user-images.githubusercontent.com/14914918/28944622-44e6462a-7871-11e7-8e12-e4fd84574af5.JPG)

Vertical bar chart, ungrouped
![143_vertical_ungrouped](https://user-images.githubusercontent.com/14914918/28944616-42fb5ada-7871-11e7-8509-5d7709844333.JPG)

Horizontal bar chart, grouped
![143_horizontal_grouped](https://user-images.githubusercontent.com/14914918/28944768-c143753a-7871-11e7-80a1-e5d04f9a3f16.JPG)

Horizontal bar chart, ungrouped
![143_horizontal_ungrouped](https://user-images.githubusercontent.com/14914918/28944609-3d2b1118-7871-11e7-8510-beb2bf7699cc.JPG)
