### ISSUE TITLE
Standardize Titles/Instructions across Tabs

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#146]
Add 2 new divs (used in all tabs):

`title` - below nav, but above controls. Header showing the `dataName` setting ([wiki](https://github.com/RhoInc/web-codebook/wiki/Codebook-Configuration#settingsdataname)) of the current file (if any) and the number of columns being summarized (vs the number being hidden). Same for every tab. Only changes when columns are hidden or a new codebook is created 

`tabHeader` - directly below controls. Explains the functionality of the given tab. Can also implement controls that are custom to a single tab (e.g. show/hide all charts for codebook)

Remove old components that overlap with this functionality.

**Comment by jwildfire** [comment]
Test Notes: Confirm that the new "title" and "tabHeader" areas (described above and highlighted below) are appearing as expected in all views. Use the `{"dataName":"myFileName"}` to confirm that the fileName can appear in the title.

**Comment by brittsikora** [comment]
Pass

![146a](https://user-images.githubusercontent.com/14914918/28845891-801fedf4-76d7-11e7-84ef-c7364c893398.JPG)

![146b](https://user-images.githubusercontent.com/14914918/28845896-8381118a-76d7-11e7-9b7f-2a98eb512a48.JPG)

![146c](https://user-images.githubusercontent.com/14914918/28845901-85ff13d0-76d7-11e7-80f1-bf056363f571.JPG)

![146d](https://user-images.githubusercontent.com/14914918/28845902-87f1ebea-76d7-11e7-98c4-b61523dc6a69.JPG)

![146e](https://user-images.githubusercontent.com/14914918/28845905-8aec879c-76d7-11e7-8dcb-3e8bcdf5cd99.JPG)

![146f](https://user-images.githubusercontent.com/14914918/28845908-8d7a967a-76d7-11e7-9f56-f9b818a15213.JPG)
