### ISSUE TITLE
Show # (%) of rows filtered in the controls header

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#147]
This is currently shown in the header on the codebook tab, but that will be deleted in #146, and it makes more sense to do it in controls section anyway.

**Comment by jwildfire** [comment]
Test Notes: Confirm that the column count now appears next to the header in the controls section and updates as expected when filtering data.

**Comment by brittsikora** [comment]
Pass

![147a](https://user-images.githubusercontent.com/14914918/28845995-d1ffd2ec-76d7-11e7-9971-0f208a543705.JPG)

![147b](https://user-images.githubusercontent.com/14914918/28845997-d3f9c53a-76d7-11e7-8079-7e86d34d67fe.JPG)
