### ISSUE TITLE
Improve Explorer functionality. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#148]
Add ability to show a table of files within the codebook workflow (new "files" tab in the nav). User should be able to click a file to render a codebook for that file.

**Comment by jwildfire** [comment]
Initial work done in #145

**Comment by jwildfire** [comment]
_Technical Approach:_ 
Kept the explorer (almost) entirely separate from the core `createCodebook()` functionality, even though it was a bit of a pain. As a result, the intended use for the codebook remains the same: Create a data summary of a single file. 

This approach required a few technical changes in web codebook: 
- Creation of a callback that trigger after the codebook is done renderering. I also added a callback on initialization for symmetry , but it isn't used in the explorer. 
- Support for a files tab (not shown by default)
- Reworked `controlVisibility` setting with an added "disabled" option. "hidden" is now a temporary state that can vary from tab to tab.

Technical approach in`webcodebook.createExplorer()` is to specify an array of files (`settings.files`) in the settings object. This will likely require some pre-processing from users who have their metadata in a file, but I think this is preferable to accepting a path to that file as a setting (at least for now).

**Comment by jwildfire** [comment]
Test Notes: Use [this link](https://rhoinc.github.io/viz-library/examples/0012-web-codebook-explorer/example.html) to confirm the following: 

- The files tab appears, and shows a list of files. 
- Clicking a file shows the codebook for the correct file
- The title, row count and column count updates when a new file is selected. 
- Basic functionality on Codebook, Data Listing and Settings tabs work as expected.

**Comment by brittsikora** [comment]
Pass

![148a](https://user-images.githubusercontent.com/14914918/28846161-6a7fa97a-76d8-11e7-8e3a-f85e46f0d4bd.JPG)

![148b](https://user-images.githubusercontent.com/14914918/28846160-6a7f4eda-76d8-11e7-8fa0-ddc9aea16766.JPG)

![148c](https://user-images.githubusercontent.com/14914918/28846163-6a844bb0-76d8-11e7-9d78-692f049d078e.JPG)

![148d](https://user-images.githubusercontent.com/14914918/28846165-6a8b77e6-76d8-11e7-8c48-7c48b73091cf.JPG)

![148e](https://user-images.githubusercontent.com/14914918/28846162-6a810928-76d8-11e7-9d8d-e4575bdd4b24.JPG)

![148f](https://user-images.githubusercontent.com/14914918/28846164-6a85ae42-76d8-11e7-9cbd-0310fb8457d4.JPG)
