### ISSUE TITLE
Add option to import generic column-level metadata in codebook

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#149]
pass in 1-record per file per column metadata object, and then add a section to each variable summary that shows the metadata for the variable.

**Comment by jwildfire** [comment]
Add new settings for both `codebook` and `explorer`. Will use this issue for the `codebook` updates and make a separate issue for adding column meta data support to the explorer. 

For `codebook`, we'll add the following new configuration options:
- `config.meta`: an array with one object per column defining metadata for that column ("Description", "Length", etc). 
- `config.metaMapping`: an object that specifies which properties of the `config.meta[]` objects correspond to settings used in the codebook. Will look like this: `{"column":"colName", "label":"labelName", "hidden":"hiddenStatus"}`. 

Settings specified in `config.meta` will take precedence over default settings, but can be overridden by user-specified settings in the `config` object or on the `settings` tab. 

Only new user-facing functionality is that properties defined in the `config.meta` object will be  shown in the header for the variable summary on the codebook page. This will require a bit of re-factoring/standardization. Will add annotated screenshot with updated layout later.

**Comment by jwildfire** [comment]
On second thought, going to  start simple and hardcode the `config.metaMapping` concept via more strict requirements in `config.meta` for now, and leave the mapping to the user. As a result, the following will be properties will be required in `config.meta`:

-`config.meta[].col_name` __required__ - the name of the column in the data
-`config.meta[].label` - label for the variable (if any). 

Not going to support specifying `filters`, `groups` or `hidden` via metadata for now.

**Comment by jwildfire** [comment]
Documented in [wiki](https://github.com/RhoInc/web-codebook/wiki/Codebook-Configuration#settingsmeta)

**Comment by jwildfire** [comment]
Test Notes: In general, confirm that metadata is rendered in "meta" view for row headers in the "summary table" tab as expected. Detailed notes below. 

Use the following settings in CAT: 
```
 {
      "variableLabels":[
        {"value_col":"hp","label":"Horse Power"},
        {"value_col":"cyl","label":"Cylinders"},
        {"value_col":"notavar","label":"ERROR: This shouldn't renderer anywhere"}
      ],
      "meta":[
        {"value_col":"mpg","label":"Miles Per Gallon","details":"These are details","length":"123"},
        {"value_col":"cyl","label":"Cylinders (ERROR: Should be overwritten - if you see this there is a problem.)","details":"car tubes","length":321},
        {"value_col":"hp","LabelFromMeta":"HP - this should render as metadata, not a label"},
        {"value_col":"notavar","label":"ERROR: Shouldn't render","blah":"bleh","badvar":true}
      ]
    }
```

Tests: 
- Make sure the page renders as expected (even with the messy settings above)
- Make sure that column names render in the top right of each header
- Make sure that labels render for hp, cyl and mpg
- Make sure that no errors have "ERROR" included. 
- Make sure that accurate "Type" meta data renders for all rows (when "meta" is selected)
- Make sure that additional metadata renderers for mpg, cyl and hp (when "meta" is selected)

**Comment by brittsikora** [comment]
Pass 

![149](https://user-images.githubusercontent.com/14914918/29190682-086b1658-7de9-11e7-908d-688d17757851.JPG)
