### ISSUE TITLE
Move link formatting to css

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#158]
https://github.com/RhoInc/web-codebook/pull/145/files/0d768b273c1f558639068850d1f2d73370f50db0#r129315665

**Comment by jwildfire** [comment]
Test Notes: QC is sufficient. No testing needed.

**Comment by brittsikora** [comment]
QC passed - everything looks normal

![158](https://user-images.githubusercontent.com/14914918/28943562-40eaec1e-786d-11e7-9b9a-2e67c1fc1146.JPG)
