### ISSUE TITLE
Add option for larger boxplot

### ISSUE THREAD

**Issue by emmorris** [RhoInc/web-codebook#16]
Potentially add margin and offset x-axis accordingly so that boxplot has more space below histogram.  We will need to set this behind the scenes.  We will test that we can change the size of the boxplot with difference configurations.

**Comment by jwildfire** [comment]
Made the option for this histogram module via `config.histogramHeight`, but not going to expose this in the codebook module for now since it would require a bit of a restructure. Just set the height to 20 for now.  Could consider exposing this option to users later if there if there is demand.
