### ISSUE TITLE
Hide "highlight" legend in all charts

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#160]
Add a legend to the instructions instead.

**Comment by jwildfire** [comment]
Test Notes: Confirm that no legends show in any bar charts - especially after clicking a bar to initiate highlights (legend should still be present in dot plot). Confirm that a 'pseudo-legend' is present in the controls description when highlights are present ("Highlighted" should have an orange background")

**Comment by brittsikora** [comment]
Pass

Testing using commit: bfdab685c4b8e09e4d10738b0e58ce3b009e4a8c

![160a](https://user-images.githubusercontent.com/14914918/28945213-8faf08a2-7873-11e7-92cb-7f64718bab48.JPG)

![160b](https://user-images.githubusercontent.com/14914918/28945215-91b0a1ba-7873-11e7-8625-f4134fd3ec10.JPG)

![160c](https://user-images.githubusercontent.com/14914918/28945217-93b2c268-7873-11e7-8e9d-70594384fdb3.JPG)
