### ISSUE TITLE
Fix modal on vertical bars

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#161]
Currently broken after adding highlights.

**Comment by jwildfire** [comment]
@samussiah Updates needed in `charts/verticalBars/onResize.js` (where the commented code needs to be re-incorporated) and maybe in `makeTooltip.js` also. 

I think the main thing to do here is update the selector from `g.bar-group` to `g.bar-group:not(.sub)`, but I'm still getting a bit of weirdness in the highlighted charts after making that change, so going to leave this to you.

**Comment by samussiah** [comment]
Test notes: verify that tooltips on vertical bars appear regardless of whether codebook has highlighting in effect.

**Comment by brittsikora** [comment]
Pass

Tested using commit: 5a6a62f4b2cec87a60e8af6161e0dae014d25abd

Tooltips - no Highlight
![161a](https://user-images.githubusercontent.com/14914918/28942838-c53a3770-786a-11e7-964c-bd76e310d603.png)

Tooltips - Highlight
![161b](https://user-images.githubusercontent.com/14914918/28942851-cc325aee-786a-11e7-95cc-cf8f56b35bdc.png)
