### ISSUE TITLE
Update Mouseover css for bars

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#162]
- Don't highlight the orange bars on mouseover
- consider adding a border instead of using the blue fill ...

**Comment by jwildfire** [comment]
Test Notes: Confirm that bars in all charts get a thick black border instead of a blue fill on hover.

**Comment by brittsikora** [comment]
What if there is both the black outline and the blue fill?

Tested using commit: 5c5d470fb136198cab6f18d452702e2842311cfe

![162](https://user-images.githubusercontent.com/14914918/28945114-1c20de38-7873-11e7-900b-8ffcccbb97fc.png)

**Comment by jwildfire** [comment]
Should be black outline only. I'll take a look and let you know when it's fixed.

**Comment by brittsikora** [comment]
Pass

this was an issue in CAT with loading older versions and the CSS not being removed

![162a](https://user-images.githubusercontent.com/14914918/28978113-c11ae0e2-7912-11e7-97e1-f5f01a487156.png)
