### ISSUE TITLE
Fix NaN in continuous variable headers

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#167]
<img width="149" alt="screen shot 2017-07-27 at 6 51 15 pm" src="https://user-images.githubusercontent.com/3680095/28699142-b98b7416-72fc-11e7-89a8-7890a9a2dd2f.png">

**Comment by jwildfire** [comment]
Test notes: Confirm that min/max values render as expected.

**Comment by brittsikora** [comment]
Pass

Tested using commit: 59ab1e01781d88cfc85d13d50e364eb5b805af1f

![167](https://user-images.githubusercontent.com/14914918/28942969-26efc16a-786b-11e7-93b3-437a5e1833b9.JPG)
