### ISSUE TITLE
Add option to import generic column-level metadata in explorer

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#169]
Add support for column-level metadata in the `explorer` method via a `config.meta` array with one object per data set per column. `explorer` will then pass the relevant columns to `codebook`  when a given file is summarized (via the codebook's separate `config.meta` object described in #149).

**Comment by jwildfire** [comment]
Similar to #149, each object in the `config.meta` array must have a `file` property and a`col_name` property to be rendered as expected.

**Comment by jwildfire** [comment]
Documented in [wiki](https://github.com/RhoInc/web-codebook/wiki/Explorer-Configuration#settingsmeta)

**Comment by jwildfire** [comment]
Test Notes: Use example 264 to confirm that column metadata is rendered on the codebook view for all files.

**Comment by brittsikora** [comment]
Pass

![169](https://user-images.githubusercontent.com/14914918/29189878-198653c4-7de6-11e7-90ba-c889395217b9.JPG)
