### ISSUE TITLE
Refactor header view in Summary Table Tab

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#181]
Update/Simplify the row headers in the codebook tab. Instead of a single view combining a value listing with summary statistics, allow the user to toggle between "Stats", "Values", "Meta" and "None"

**Comment by jwildfire** [comment]
Test Notes: Confirm that the toggles (both in the header for the codebook, and in the individual rows) work as expected.

**Comment by brittsikora** [comment]
Pass

Header: Meta
![181a](https://user-images.githubusercontent.com/14914918/29188399-f8391a30-7de0-11e7-9d12-29d09a54dc04.JPG)

Header: Meta; Individual: Values
![181b](https://user-images.githubusercontent.com/14914918/29188407-fb2173d2-7de0-11e7-9db3-1945529ea36a.JPG)

Header: None
![181c](https://user-images.githubusercontent.com/14914918/29188411-fcd86e1a-7de0-11e7-88c6-377f765d9392.JPG)
