### ISSUE TITLE
Allow users to add files after explorer is initialized

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#191]
Basically the user would just pass additional valid `settings.files[]` objects to a new `explorer.addFiles()` method. would be used in conjunction with https://github.com/RhoInc/codebook/issues/8

**Comment by jwildfire** [comment]
Would be nice to format the file input like this: https://stackoverflow.com/questions/572768/styling-an-input-type-file-button

**Comment by jwildfire** [comment]
## Test Notes
Use the [explorer test page](https://rawgit.com/RhoInc/web-codebook/v1.5.0-dev/test-page/explorer.html) to confirm that you can add csv files from your hard drive to the file list and that they have functional codebooks once loaded.

**Comment by danedexF5** [comment]
Chrome and FF both loaded 2 different CSVs and they functioned as expected.
