### ISSUE TITLE
Make config option to hide codebook charts on initial load

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#198]
SDF request: "I wonder if the default should be to hide all graphs and then click on the ones you want. Most of our datasets have a lot of variables where we wouldn’t want to see the figures for all variables"

**Comment by jwildfire** [comment]
Modeled off `config.controlVisibility`. Added [documentation to wiki](https://github.com/RhoInc/web-codebook/wiki/Codebook-Configuration#settingschartvisibility). Thinking about making "minimized" the default. Thinking it will help load times as well since the charts wouldn't renderer until the user maximizes them.

**Comment by jwildfire** [comment]
Test Notes: Try the following settings in CAT, and make sure that charts minimize and maximize as described in wiki docs.

- `{"chartVisibility":"minimized"}` (confirm that this is the default when no settings are provided)
- `{"chartVisibility":"visible"}`
- `{"chartVisibility":"hidden"}`

**Comment by dschwentker** [comment]
web-codebook confirmed to now default to showing the charts as minimized. Can toggle them to visible and then back to minimized using chartVisibility settings. Per Spencer, hidden has been deprecated and no longer works.
