### ISSUE TITLE
Update codebook.explorer table calls

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#202]
Tweak file table presentation to use webcharts v1.9

**Comment by jwildfire** [comment]
Test Notes: Confirm that files tab at ./projects/264/testing/202.html works as expected (click a file link to see a codebook, and doesn't have any sort/search/pagination/export functionality shown by default.

**Comment by dschwentker** [comment]
Confirmed that files tab at http://interactive.it.rhoworld.com/dev/projects/264/testing/202.html works as expected in all browsers.
