### ISSUE TITLE
explorer bombs on init when config.meta isn't specified

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#203]
Make sure it's defaulting to `[]` and not `null`

<img width="808" alt="screen shot 2017-10-04 at 6 25 31 am" src="https://user-images.githubusercontent.com/3680095/31178131-f9323f2c-a8cc-11e7-8f7a-34bf7fd6cc52.png">

**Comment by jwildfire** [comment]
Test Notes: Make sure that charts load with no meta data specified in  ./projects/264/testing/203_fixed.html in latest build. Buggy version (using v1.2 release) can be viewed in projects/264/testing/203_broken.html.

**Comment by dschwentker** [comment]
Confirmed that charts load with no meta data specified via http://interactive.it.rhoworld.com/dev/projects/264/testing/203_fixed.html in all browsers.
