### ISSUE TITLE
Add new chart maker module

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#205]
Overview: Add a new tab allowing users to create custom charts comparing 2 variables from the raw data set 

Details:  Data is encoded in 4 ways in the chart maker tab: 
1. x-axis - the user can select any column from raw data
2. y-axis - the user can select any column from raw data
3. panel - the user can any variable eligible that can be used a group in the codebook (can be updated in settings)
4. point color - not customized by the user. Instead, this shows highlighted points from the codebook tab, if any. Note that this encoding is not used when both the x- and y- axis variables are categorical (and thus there are no points, only bars). 

There are 4 chart types supported in the charting tab, as shown below. 
1. scatter plot (x and y are continuous)
<img width="522" alt="screen shot 2017-10-30 at 6 57 02 pm" src="https://user-images.githubusercontent.com/3680095/32204034-3277c3d8-bda4-11e7-826c-fb4564981020.png">

2. horizontal dot plot (x is continuous, y is categorical)
<img width="514" alt="screen shot 2017-10-30 at 6 56 12 pm" src="https://user-images.githubusercontent.com/3680095/32204069-6574a026-bda4-11e7-828c-bf80319e26e9.png">

3. vertical dot plot (x is categorical, y is continuous)
<img width="497" alt="screen shot 2017-10-30 at 6 53 47 pm" src="https://user-images.githubusercontent.com/3680095/32203962-c228df5e-bda3-11e7-8a85-5e2876541fe9.png">

4. stacked bar chart (x and y are categorical)
<img width="504" alt="screen shot 2017-10-30 at 6 55 08 pm" src="https://user-images.githubusercontent.com/3680095/32203990-e5e648dc-bda3-11e7-98b9-7964594dcb8a.png">

Note that all 4 chart types work with or without a panels - that is, with or without a group by variable selected.

**Comment by jwildfire** [comment]
Test notes: On the new charts tab, confirm the following: 
- The 4 chart types above render as expected (note that you can tell which variables are continuous vs. categorical by setting header type to "meta" on the codebook tab)
- Filters are functional on all chart types
- Grouping works as expected on the 4 chart types
- Highlighted points appear as expected on charts 1, 2 and 3.

**Comment by dschwentker** [comment]
Tested and confirmed all four charts render and filter as expected in all browsers. Grouping works as expected and the legend is now hidden for all charts except type 4.
