### ISSUE TITLE
Data Listing controls are not working in IE 11

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/web-codebook#208]
When viewing the web-codebook renderer (version f5b2a4c125445ddd6832a46688d7291c61104179 and Webcharts Version v1.9.0-RC3) in IE 11, the Controls section does not seem to work. I can click on different options within the various controls, but none of them operate to change the records listed in the table. When the renderer loads, all of the options are selected by default, but when try to click on an option (or ctrl + click) multiple options, it doesn't make the clicked options selected and the others in the list unselected, but it leaves the options I didn't click on highlighted in blue and highlights the options I did click on in gray.

![image](https://user-images.githubusercontent.com/17090469/31457263-46a8469e-ae8a-11e7-93bf-2dae2b978fd9.png)

**Comment by brittsikora** [comment]
Fixed in latest version
