### ISSUE TITLE
Make option for independent axes across panels when grouping

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#210]
Allow for independent chart scaling when grouping by a variable - it would be nice if a user could tell codebook for a certain variable to scale each plot differently. For example, if you group by lab test in a vital sign dataset, you get 1 plot for each test on a scale from 0-160. This produces a nice plot for blood pressure & heart rate, but not for temperature.  SDTM and ADaM datasets are vertical, often with a test/parameter variable.

(From SDF)

**Comment by jwildfire** [comment]
Most important use case is probably for continuous measures since categorical charts already have an option to toggle between # and %. 

To implement, we can add a "commonScale" option to each continuous variable that determines whether the panels in the histogram/boxplot renderer have a common scale (the current default) or not. Leaning towards not making this configurable for now - it can just be set via the user in the chart controls. 

Key code in the renderer is [here](https://github.com/RhoInc/web-codebook/blob/master/src/charts/histogramBoxPlot/onInit.js#L43-L48). Will also need a new `./charts/createHistogramBoxPlotControls/js` method to handle the toggle.

**Comment by jwildfire** [comment]
Test Notes: 
- No changes when no group variable is specified
- When group is specified a new "Standardize x-axis?" checkbox should be visible for continuous variables. 
- When checkbox is clicked, all x- and y-axis should have the same range for all panels. 
- When checkbox is not clicked, x- and y-axis should vary to match the range for each individual panel. 

For a good test case (matching the SDF request above): 
- Load`ADBDC.csv` in cat
- Click hide all charts
- Open Settings tab and check 'group' column for the 'test' row
- Open codebook tab and group by test
- Expand the "STRESN" chart. Notice the tiny histograms for most panels
- Unselect the  "Standardize axes across panels?" checkbox, and observe the improved histograms

**Comment by dschwentker** [comment]
Tested and confirmed functionality of new "Standardize axes across panels?" checkbox in all browsers.
