### ISSUE TITLE
Allow users to provide custom labels for tabs

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#212]

**Comment by jwildfire** [comment]
Added via `config.tabs`. Wiki Documentation added [here](https://github.com/RhoInc/web-codebook/wiki/Codebook-Configuration#settingstabs)

**Comment by jwildfire** [comment]
Test Notes: Confirm that the settings object below creates a codebook with just the given tabs with the custom labels and instructions as specified: 

```
{
  "tabs":[
    "codebook",
    {key:"settings",label:"Settingz","instructions":"Set!"}
  ]
}
```

**Comment by dschwentker** [comment]
Confirmed settings object can create custom tabs and labels in all browsers.
