### ISSUE TITLE
New charts are appearing very small/illegible in Firefox when using Grouping

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/web-codebook#218]
The new charts in web-codebook look good, except for when I use the Group by filter in Firefox. When I use that, the charts get much smaller, with overlapping text/plots and they are basically illegible. I do not see the same problem in either Chrome or IE 11. I'm using version 56.0.2, which should be up to date.

![image](https://user-images.githubusercontent.com/17090469/32247752-bb76384e-be59-11e7-9369-2472eb5e4016.png)

**Comment by jwildfire** [comment]
Changing to fixed width seems to fix the bug.

**Comment by dschwentker** [comment]
Confirmed this bug is fixed in Firefox, and charts still appear in their expected size in Chrome and IE 11.
