### ISSUE TITLE
Fix uncaught errors when data is filtered to 0 records

### ISSUE THREAD

**Issue by mhickle** [RhoInc/web-codebook#221]
Loading icon appears and continues to blink when the Codebook is filtered down to "no rows selected" message.

**Comment by jwildfire** [comment]
This happens outside of RhoMap as well.

**Comment by jwildfire** [comment]
Was due to an uncaught error in the charting module.

**Comment by jwildfire** [comment]
Test Notes: Filter the data down to 0 items and click on each tab to make sure there are good notes and no horrific errors like the one shown abvoe.

**Comment by mhickle** [comment]
Pass 

![2](https://user-images.githubusercontent.com/31038805/33385838-966f310e-d4f7-11e7-87a0-4605de430068.PNG)
