### ISSUE TITLE
CB Styling Issues in RhoMap

### ISSUE THREAD

**Issue by mhickle** [RhoInc/web-codebook#222]
Styling issues with the header of Codebook
![10](https://user-images.githubusercontent.com/31038805/32904689-eca24548-cac5-11e7-9b81-6d940aa5e0b9.PNG)

**Comment by jwildfire** [comment]
I'm wondering if RhoMap is still using an old version of the CSS ...

**Comment by jwildfire** [comment]
Confirmed. This will likely be resolved when the updated css is added.

**Comment by jwildfire** [comment]
Confirm that this is fixed when correct css is loaded and close this issue (I've added the invalid tag).
