### ISSUE TITLE
Refactor loading indicator

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#224]
Get rid of `/src/codebook/util/indicateLoading.js` and implement a solution that doesn't use setInterval()

**Comment by jwildfire** [comment]
Didn't totally refactor the approach, so we're still using `setInterval`), but did add some error handling to avoid the spectacular interactive crashes like the one shown in #219. Also changed appearance via css a bit to make it more obvious when load is occurring.

**Comment by jwildfire** [comment]
Test Notes: Confirm that loading icon appears in upper right hand corner when loading the page, filtering, grouping, etc. Easiest to test with a large data set.

**Comment by mhickle** [comment]
Pass
