### ISSUE TITLE
ReadMe Images

### ISSUE THREAD

**Issue by mhickle** [RhoInc/web-codebook#230]
![gif1](https://user-images.githubusercontent.com/31038805/33682586-fb48c2cc-da95-11e7-87d9-79982b1aa8ed.gif)

**Comment by mhickle** [comment]
![gif2](https://user-images.githubusercontent.com/31038805/33683185-0f6d9c44-da98-11e7-829d-24f41e77ffc2.gif)

**Comment by mhickle** [comment]
![6](https://user-images.githubusercontent.com/31038805/33946994-41bde7cc-dff1-11e7-9cac-0ea8b23c872f.PNG)

**Comment by emmorris** [comment]
No development or testing involved.  Just a placeholder issue with images.
