### ISSUE TITLE
`clone` sets of stack size error in certain situations

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#234]
Here are the details on the codebook issue:

1. Load up an Adverse Event file
2. Show All Charts and Group by anything, say Race.
3. In the first chart, uncheck 'Standardize axes across panels'.
4. That sets off call stack errors in chrome ("maximum call stack size exceeded" pointing to lines 59 and 68 in the clone() function), and similar unhappiness/hanging in firefox.

That error can mean there's a recursive loop in the data we're cloning, or just that we stacked up so many function calls the browser's queue of things to run filled up. In case it was the former, i found a version of clone online that checks for circular references, and adapted it into webcodebook.js, and the error no longer occurs. 

So, this might mean there's an infinite loop in the code to track down, but it occurred to me after i did it that it's also possible all i did was slow down some of the processing to the point the browser stack never filled up.

**Comment by samussiah** [comment]
Can't reproduce.  Maybe my computer's too roided out to notice.

**Comment by jwildfire** [comment]
Leaning towards calling this an edge case until we get a confirmed report in production. Marking "Low Priority" for now.

**Comment by jwildfire** [comment]
Going to close unless/until we can reproduce.
