### ISSUE TITLE
Add test page.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#244]
# Test Notes

Confirm that the [test page](https://rawgit.com/RhoInc/web-codebook/refactor-summary-row/build/test-page/) looks good and works as expected.

**Comment by jwildfire** [comment]
@samussiah The link above is loading from the master branch for me ... Having problems with viewing the pages locally too - hence [local.html](https://github.com/RhoInc/web-codebook/blob/refactor-summary-row/build/test-page/local.html) and [local-explorer.html](https://github.com/RhoInc/web-codebook/blob/refactor-summary-row/build/test-page/local-explorer.html).

Any debug ideas?
