### ISSUE TITLE
web-codebook test page not working correctly in IE

### ISSUE THREAD

**Issue by danedexF5** [RhoInc/web-codebook#268]
The test page with this address: https://rawgit.com/RhoInc/web-codebook/refactor-summary-row/build/test-page/  opens in IE as expected. 
The test page with this address: https://rawgit.com/RhoInc/web-codebook/refactor-summary-row/build/test-page/explorer.html  does not fully render. Only the title appears.

**Comment by jwildfire** [comment]
Going to call this a duplicate with #273
