### ISSUE TITLE
Different display for many unique values

### ISSUE THREAD

**Issue by sjlussier** [RhoInc/web-codebook#278]
For variables with a large number of unique variables, the graphic produced is not very informative. 

As an example the following dataset's "id" variable:

```
dat <- tibble(a = rep('01', 100),
              b = sample(c('02', '03', '07', '09'), 100, replace = T),
              c = sample(1000:9999, 100, replace = T)) %>%
   mutate(id = glue("{a}-{b}-{c}"),
         site = sample(c("bost", "nyc", "phil", "chic", "la", "sd", "sf"), 100, replace = T)) %>%
  select(id, site)
```

![image](https://user-images.githubusercontent.com/41168885/43660313-9aa5af44-972c-11e8-9ae0-6bdeb7adb824.png)

One solution may be to just suppress the graphic.

**Comment by jwildfire** [comment]
@sjlussier Yeah, that display is meh for sure. We have a possible solution tracked as issue #50. Would that help?

**Comment by sjlussier** [comment]
Yes, I do think that would help!

**Comment by jwildfire** [comment]
👍Closing this one. Will address #50 in the next release.
