### ISSUE TITLE
Uniquely identify data files in the explorer.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#283]
![image](https://user-images.githubusercontent.com/5428548/44098009-0a06829a-9fad-11e8-8bfc-8ad5c6f788fc.png)

**Comment by jwildfire** [comment]
Adding a new `fileID` property to each item in `explorer.settings.files` and using that instead of `labelColumn` as the identifier

**Comment by jwildfire** [comment]
## Test Notes

Use the file load control on the explorer [test page](https://rawgit.com/RhoInc/web-codebook/v1.5.0-dev/test-page/explorer.html) to load the same file twice. Confirm that both files are shown in the file list, but only one file is highlighted. Check that both codebooks work.

**Comment by danedexF5** [comment]
Works as expected in chrome and FF. Both files appear, only one is highlighted and they work in codebook.
