### ISSUE TITLE
Make file loader optional

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#290]

**Comment by jwildfire** [comment]
Adding boolean `explorer.config.fileLoader`.

**Comment by jwildfire** [comment]
## Test Notes

Confirm that the fileLoader control isn't shown when you use the settings input at the bottom explorer [test page](https://rawgit.com/RhoInc/web-codebook/v1.5.0-dev/test-page/explorer.html) to change the fileLoader setting from `true` to `false`

**Comment by danedexF5** [comment]
Working as expected. When true is changed to false, the File Loader control no longer appears.
