### ISSUE TITLE
Varable type changes when filtering

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/web-codebook#30]
When filtering on a variable (ex. age), the variable changed from categorical to continuous

![cat_con](https://cloud.githubusercontent.com/assets/14914918/24518400/dc6b5470-154f-11e7-9c1b-9f6752ca9d86.JPG)
![cat_con_2](https://cloud.githubusercontent.com/assets/14914918/24518399/dc675442-154f-11e7-8b55-3c0c61c5e4a4.JPG)

**Comment by jwildfire** [comment]
This behaviour is expected, but not sure if it is desirable or not ...

**Comment by jwildfire** [comment]
Probably best to have the variable type stay constant as data is filtered, especially if we implement #266.

**Comment by jwildfire** [comment]
Currently, variables with type specified by the user will be constant, but automatic detection will be re-run after filter ... probably want to change that, but arguably not as urgent now.

**Comment by jwildfire** [comment]
Marking as won't fix. If changing type when filtering is an issue, Work-around is for user to specify a type.
