### ISSUE TITLE
Error message not displaying

### ISSUE THREAD

**Issue by danedexF5** [RhoInc/web-codebook#308]
Going through regression tests for 1.6 and noticed that when filtering down to values that do not match any data points, an error message does not display. I spoke with Jeremy about it, he said it shouldn't delay this release but it'll get fixed for a future release.

**Comment by dschwentker** [comment]
Confirmed that a "No values selected. Update the filters above or load a different data set." message appears when the data is filtered down to values that do not match any data points during regression testing.
