### ISSUE TITLE
Histograms won't renderer certain group variables

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#33]
<img width="1010" alt="screen shot 2017-04-05 at 1 41 28 pm" src="https://cloud.githubusercontent.com/assets/3680095/24726019/b778255c-1a05-11e7-82b0-ccd3d71dba41.png">
<img width="426" alt="screen shot 2017-04-05 at 1 40 49 pm" src="https://cloud.githubusercontent.com/assets/3680095/24726018/b772f898-1a05-11e7-9fbd-c8149f6a2fb5.png">

**Comment by jwildfire** [comment]
Pretty sure this happens when one of the levels is blank - that is when `d.AESER==""`

**Comment by jwildfire** [comment]
Test Notes: Just confirm that everything renders as expected after changing the group by control in dev-v1.0.0. Make sure to check for a group by variable with blank values - like AESER above.

**Comment by brittsikora** [comment]
Expected Outcome: Grouped data by SEX and AESER and all charts rendered

Outcome: Pass
