### ISSUE TITLE
Fix div alignment.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#34]
![image](https://cloud.githubusercontent.com/assets/5428548/24726136/4ae573ee-1a1f-11e7-9531-6ae5f42d0a9a.png)

**Comment by jwildfire** [comment]
change the alignment to 'block'

**Comment by jwildfire** [comment]
@samussiah messing with css for showing/hiding charts, so fixed this as well.

**Comment by brittsikora** [comment]
Functional Test: Current version lines up vertically and looks as expected

Pass
