### ISSUE TITLE
Add control (or setting) to choose between dot plots and bar charts for categorical outcomes.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#41]

**Comment by jwildfire** [comment]
This is going go to be chart-by-chart instead of codebook wide.

**Comment by jwildfire** [comment]
allow users to choose between "paneled" (bar charts) and "grouped" (dot plots) when a) a group variable is active and b) there are <5 levels in the categorical variables

**Comment by brittsikora** [comment]
Expected Result: When the data is filtered by group the option to choose between paneled and grouped charts should appear for categorical variables with >5 levels
![categorical_no_group](https://cloud.githubusercontent.com/assets/14914918/25100330/acaa6f50-237d-11e7-8545-f474d9ebb43b.JPG)
![categorical_group](https://cloud.githubusercontent.com/assets/14914918/25100329/aca99f1c-237d-11e7-96c7-3793456f2b30.JPG)



Outcome: Pass
