### ISSUE TITLE
Indent the section headers

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#43]
Bring "Sex: M" etc off the edge. 

<img width="817" alt="screen shot 2017-04-10 at 9 27 49 am" src="https://cloud.githubusercontent.com/assets/3680095/24871885/0d753f08-1dd0-11e7-9880-24a228064713.png">

**Comment by brittsikora** [comment]
Functional Test: Variables indented now
![indents](https://cloud.githubusercontent.com/assets/14914918/25056996/9267a2d8-213a-11e7-94e6-45e9b796a8dc.JPG)

Pass
