### ISSUE TITLE
Create new chart for categorical variables with >5 levels

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#44]
When a categorical variables has more than 5 levels, render a bar chart showing *all* levels with y-axis = prevelance and x-axis = level. Hide the x-axis labels, and instead show the level name, number of observations and % of observations on mouseover. 

This should do a better job showing the distribution for categorical variables with lots of levels (participant ID, etc).

**Comment by brittsikora** [comment]
Expected Result: Categorical variables with more than 5 levels should receive a vertical bar chart with y-axis = prevelance and x-axis = levels.

Outcome: Pass
