### ISSUE TITLE
Add control that toggles how categorical bars are sorted

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#46]
Descending prevalence, ascending prevalence or alphabetical

**Comment by brittsikora** [comment]
Expected Result: Categorical bar charts have a control that allows the user to sort the chart on descending prevalence, ascending prevalence, or alphabetically

Outcome: Pass
![bar_chart_sort](https://cloud.githubusercontent.com/assets/14914918/25097738/c0d03aaa-2373-11e7-8cea-d8b77c9e25aa.png)
