### ISSUE TITLE
Make a setting for the cut point used to switch between renderers for categorical variables

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#49]
Currently, `makeBarChart()` is used for variables with 0-5 levels and `makeLevelChart()` is used for 6+ levels. Right now this is just hard coded [here](https://github.com/RhoInc/web-codebook/blob/high-level-bars/src/chart/summaryTable/renderRow/makeChart.js#L15) and [here](https://github.com/RhoInc/web-codebook/blob/high-level-bars/src/chart/summaryTable/renderRow/makeChart/makeBarChart.js#L47) and perhaps elsewhere too ...

**Comment by jwildfire** [comment]
implemented as `levelSplit` option.

**Comment by brittsikora** [comment]
Expected Result: Using the CAT, change the level split in the settings to show variables as horizontal bar charts. The default level split is 5, so change {"levelSplit":x} to something else and render the chart again to see vertical bar charts become horizontal

Outcome: Pass
