### ISSUE TITLE
Create a setting for maximum # of levels allowed in a categorical variable. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#50]
Default = 200ish? Start to see performance issues after that, especially when viewing grouped displays.

**Comment by jwildfire** [comment]
Should be pretty easy to implement. Would just probably just hide categorical variables with more than the specified number of levels by default.

**Comment by dschwentker** [comment]
Confirmed maxLevels can be used as a setting to change maximum # of level allowed in a categorical variable in Codebook charts.
