### ISSUE TITLE
Y axis labels on box-plot cut for values > 999

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#51]
:(

<img width="434" alt="screen shot 2017-04-11 at 8 47 39 am" src="https://cloud.githubusercontent.com/assets/3680095/24917958/9ad1efa4-1e93-11e7-9029-b78e292bce57.png">

**Comment by jwildfire** [comment]
Consider moving y-axis to the right hand side? (says @emmorris)

**Comment by brittsikora** [comment]
Issue fixed with #52
