### ISSUE TITLE
Add count on x-axis

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/web-codebook#60]
Feedback from the SDF meeting on 4/13. Karen Boyle said it would be helpful to see the x-axis of some of the charts shown in counts instead of percentages.

**Comment by jwildfire** [comment]
This would probably done via a toggle on the categorical bar charts.

**Comment by jwildfire** [comment]
Toggle could work (as mentioned above). We could also consider: 
- Showing counts when a user mouses-over the axis. 
- Adding a 2nd axis on the top/right of the chart with counts.

**Comment by emmorris** [comment]
Maybe start with toggle and improve down the road.

**Comment by brittsikora** [comment]
Expected outcome: User can summarize categorical bar charts by counts in addition to percentages

Result: Pass

![image](https://user-images.githubusercontent.com/14914918/27450976-8259b320-575b-11e7-8957-a5c6ad46c13d.png)
