### ISSUE TITLE
Strange behavior on re-size

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#62]
Charts are rendering outside of their wrapper. 

<img width="757" alt="screen shot 2017-04-14 at 2 43 48 pm" src="https://cloud.githubusercontent.com/assets/3680095/25056921/cf8abdcc-2120-11e7-8294-f4eb2dc9b36c.png">

**Comment by jwildfire** [comment]
This is because the `div.variable-row` width is set to 100%, but the charts aren't resizable (since we want a fixed height). Best bet is just to set the whole thing to a fixed width (ie: 1024px).

**Comment by jwildfire** [comment]
Test Notes: Just confirm that the chart doesn't overlap the div border as shown in the screenshot in dev-v1.0.0

**Comment by brittsikora** [comment]
Expected Result: Viewed all charts and they all are contained in their wrappers

Outcome: Pass
