### ISSUE TITLE
Chart Renders infinitely 

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/web-codebook#63]
To reproduce:

    Pull up CAT in FireFox: https://jwildfire.github.io/CAT/
    Confirm the renderer is web-codebook renderer
    Input version as: ded094e
    Confirm data file is safetyData-queries/ADAE.csv
    Click "Render Chart"
    Click the grey arrow next to the AGE to expand the chart
    Watch the chart expand for all eternity
![1912_8851](https://cloud.githubusercontent.com/assets/14914918/25100679/01f558c0-237f-11e7-90af-ae11d82aeec0.png)

**Comment by jwildfire** [comment]
This happens because the `getbbox` implementation is a bit inconsistent across browsers. Bombs in firefox and IE. Not quite sure why this causes the chart to renderer endlessly though ...

**Comment by jwildfire** [comment]
The text needs to be visible when getbbox is called in FF and IE. Removing this bit of css fixes the bug: 
 
```
.web-codebook .summaryTable .variable-row .row-chart .tooltip {
   display: none;
}
```

Of course, now all of the tooltips are visible at the same time. I'm thinking we'll just hide them immediately after calling `getbbox`

**Comment by jwildfire** [comment]
Left the css the same, but set the `tooltip` class *after* calling `getBBox()`, which seems to do the trick in FF.

**Comment by jwildfire** [comment]
Test Notes: Just confirm that everything renders as expected in dev-v1.0.0

**Comment by brittsikora** [comment]
Expected Result: Opted to "Show All Charts" and each chart rendered once.

Outcome: Pass
