### ISSUE TITLE
Fix viz-library examples

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#64]
Fix: https://rhoinc.github.io/viz-library/examples/0009-web-codebook-demo/

Add examples for `.makeExplorer()`

**Comment by emmorris** [comment]
We should make sure that we update the "Click here for a live demo" link in the codebook wiki with the link to the updated example too.

**Comment by emmorris** [comment]
@samussiah updated the viz-library with the latest 1.0.0 code.  The new example appears to have the latest updates with the row height being fixed and the wiki link points to the updated example, so this can be closed now.
