### ISSUE TITLE
Improve default handling for `filters` and `groups`

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#65]
If a user passes in an array of text (e.g. `groups:["sex","race"]`) then `setDefaults` should `.map()` it in to an appropriate array of objects.

**Comment by jwildfire** [comment]
try renderering in version = dev-v1.0.0 with the following settings:`{filters:["SEX","RACE"], groups:["SEX","ARM"]}`

**Comment by samussiah** [comment]
CAT requires JSON syntax:
```javascript
{
  "filters": ["SEX", "RACE"],
  "groups": ["SEX", "ARM"]
}
```

**Comment by brittsikora** [comment]
Expected Result: Used the following settings in the CAT to render only those filters and groups:

{
"filters": ["SEX", "RACE"],
"groups": ["SEX", "ARM"]
}

Outcome: Pass
![groups_filters](https://cloud.githubusercontent.com/assets/14914918/25389723/634f2062-299f-11e7-90af-0944cfee9322.png)
