### ISSUE TITLE
Add bar charts for categorical variables

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#7]
Add a toggle that lets a user toggle between dot plots and bar charts for categorical variables. 

Bar charts are simple enough without grouping variables, but when there is an active grouping (e.g. site), draw one panel per level like the SAS implementation [here](https://github.com/RhoInc/sas-codebook/wiki/Panels-%5BPre-production%5D)

**Comment by jwildfire** [comment]
bulk of this was done in 8204d7294849caf869cf5b6d0e2701175b3a8b49

**Comment by brittsikora** [comment]
Test: Toggle appears when data is grouped by a variable, standard bar chart appears as a default for categorical data

Pass
