### ISSUE TITLE
add createChart alias for createCodebook

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#70]
Up through v0.11.0 we used createChart to create Codebooks (createChart is used in almost all other renders also). v1.0.0 is going to move to createCodebook as the standard (since the object created is a `codebook` object containing lots of webcharts `chart` objects), but for convenience, let's support createChart() as an alias as well.

**Comment by samussiah** [comment]
Ah, makes sense now.

**Comment by jwildfire** [comment]
Testing note: Can confirm by changing the 2nd part of the init control from 'createCodebook' to 'createChart' for version = dev-v1.0.0 and making sure the chart still renders.

**Comment by brittsikora** [comment]
Expected Result: Changed the second part of the init control from 'createCodebook' to 'createChart' and the chart rendered as expected

Outcome: Pass
