### ISSUE TITLE
Add loading indicator

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#75]
This is mostly needed on initial load, on filter and (especially) when the group by selection changes.

**Comment by jwildfire** [comment]
On the fence about whether this is a priority for v1.1. Adding it for now.

**Comment by brittsikora** [comment]
Expected outcome: A loading indicator appears when a user makes a change using the ui

Result: Pass

![75](https://user-images.githubusercontent.com/14914918/27449505-a4b3a1e2-5756-11e7-9e01-f6d756fa9a52.png)
