### ISSUE TITLE
Panel Label overlaps y-axis on grouped histograms.

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#77]
screenshot below. Move label above each panel (like bar charts).
<img width="1039" alt="screen shot 2017-04-19 at 2 34 28 pm" src="https://cloud.githubusercontent.com/assets/3680095/25203274/7d7a86d4-250d-11e7-9b21-90a497c3f7fb.png">

**Comment by jwildfire** [comment]
Test Notes: Confirm that the label now renders above the chart in dev-v1.0.0

**Comment by brittsikora** [comment]
Expected Result: When the user groups the data by a variable, the histogram shows the grouping variable on the top-left of each histogram

Outcome: Pass
![histogram_grouping](https://cloud.githubusercontent.com/assets/14914918/25356519/67cf8d76-2908-11e7-8ff8-8943c35bf7d6.JPG)
