### ISSUE TITLE
Huge row headers (CSS issue)

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#80]
Getting huge row-headers in the [viz-library example](https://rhoinc.github.io/viz-library/examples/0009-web-codebook-demo/example.html). Just need to remove `height:100%` [here](https://github.com/RhoInc/web-codebook/blob/dev-v1.0.0/css/webcodebook.css#L136). As shown in screenshots below. 

With Bug: 
<img width="1440" alt="screen shot 2017-04-26 at 12 25 22 am" src="https://cloud.githubusercontent.com/assets/3680095/25417049/b8c7875a-2a17-11e7-9db1-71599f74b12f.png">

With CSS fix:
<img width="1436" alt="screen shot 2017-04-26 at 12 31 49 am" src="https://cloud.githubusercontent.com/assets/3680095/25417065/ca436922-2a17-11e7-99f1-7d797975fb9b.png">

**Comment by jwildfire** [comment]
@samussiah - going to assign to you. 

@brittsikora  @emmorris - we should probably hold off on tagging v1.0.0-RC1 and starting regression testing until this is resolved.

**Comment by emmorris** [comment]
@brittsikora tested this and confirmed that it is now displaying appropriately.  The rows are no longer really tall.  Closing this now that it has been tested.
