### ISSUE TITLE
Update class of chart tooltips to avoid bootstrap CSS conflicts.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/web-codebook#85]
maybe 'svg-tooltip' instead of 'tooltip'

**Comment by jwildfire** [comment]
Test Notes: Confirm that tooltips appear as expected in the generic version of this page (without bootstrap installed), and in the application where the bug was detected (with bootstrap included). 

Use commit: 9139f6c5842b06bde3e6d4239d718fbbad33ea26 for testing.

**Comment by brittsikora** [comment]
Expected Outcome: Tooltips will appear as expected in applications with and without bootstrap

Result: Pass
