### ISSUE TITLE
Report number of unique values for categorical variables

### ISSUE THREAD

**Issue by agstn** [RhoInc/web-codebook#91]
Consider adding unique values to the categorical variables. This is a surprisingly easy way to find repeated observations when none are expected.

**Comment by jwildfire** [comment]
The number of unique values is included (in a slightly obscure way) in the header. 
 
<img width="1035" alt="screen shot 2017-05-18 at 11 13 01 am" src="https://cloud.githubusercontent.com/assets/3680095/26217114/2d73926a-3bbb-11e7-9da5-ca8d53aaebe0.png">

@agstn Do you think reporting in along with the statisitics (N, n, missing) is needed too?

**Comment by agstn** [comment]
I would suggest reporting this statistic along the more prominent ones in top/right section

**Comment by jwildfire** [comment]
Easy fix - adding to v1.1

**Comment by brittsikora** [comment]
Expected outcome: Chart shows number of unique values for a categorical variable

Result: Pass

![91](https://user-images.githubusercontent.com/14914918/27449611-fa85af16-5756-11e7-9c6a-249f96d70fdc.JPG)
