### ISSUE TITLE
Variables alphabetical sort option

### ISSUE THREAD

**Issue by agstn** [RhoInc/web-codebook#92]
Consider adding an option where the user will be able to sort the variables in the codebook alphabetically. This is especially useful when the data has lots of variables and the user is interested in checking just a few of them.

**Comment by jwildfire** [comment]
Definitely doable, but (I'd argue) pretty low priority. Can always just search for the variable name you're interested in the browser with ctrl-f

**Comment by jwildfire** [comment]
Covered by #255.
