### ISSUE TITLE
Add Show/Hide Controls toggle

### ISSUE THREAD

**Issue by agstn** [RhoInc/web-codebook#93]
Two suggestions regarding the filters section:
- Consider a button to **hide or show the filters**. I can imagine a lot of users will only interested in looking at the whole codebook and the filters are distracting
- Consider keeping the **filters always on top** of the page, even when you have scrolled past them. That way it is easy to interact with a variable that is down the page.

**Comment by jwildfire** [comment]
I like the idea of a show/hide button (and it's pretty straightforward). 

I'm a bit less sure about pinning the filters to the top of the div. Definitely possible, but it's generally good to keep our formatting and css requirements as small as possible. Will need to look in to it more ...

**Comment by bzkrouse** [comment]
This would be useful for integrating with R - would allow more flexibility in customizing the UI in apps and would allow for a UI that is applicable to both interactive and static codebooks.

**Comment by jwildfire** [comment]
Updating this issue to just cover the show/hide functionality and adding it to v1.1. Feel free to make a separate issue for the pinning filters to top if you think it's important. 

For show/hide, we should create a `config.filtersVisibility` option and an associated custom toggle. `filtersVisibility` gets the following options
- `"visible"` - filters are visible, toggle is visible
- `"hidden"` - filters are hidden, toggle is hidden
- `"minimized"` - filters are hidden, toggle is visible

I guess we could also have a fourth option for filters visible/toggle hidden, but seems like an edge case, so not sure it's needed.

**Comment by jwildfire** [comment]
Implemented in branch `filter-visibility` and documented in the [wiki](https://github.com/RhoInc/web-codebook/wiki/Codebook-Configuration#settingscontrolvisibility)

Test notes: Functionality described above can be tested in CAT with the following settings `{"controlVisibility":"hidden"}`

**Comment by brittsikora** [comment]
Expected outcome: When the settings below are entered, the user controls disappear

{"controlVisibility":"hidden"}

Result: Pass

![image](https://user-images.githubusercontent.com/14914918/27450809-f3dc38ac-575a-11e7-9c68-e36b85b84633.png)
