### ISSUE TITLE
Add option for variable labels

### ISSUE THREAD

**Issue by agstn** [RhoInc/web-codebook#94]
Is it possible to also import the variable labels from SAS and use them next to each variable names to better understand what the variable is referring to?

**Comment by jwildfire** [comment]
We could do this via a setting where users specify labels for each variable. Wouldn't be too hard to add, but might not be that easy to use in most cases either, since it would definitely require a fair amount of additional work on the users part. 

We'd leave it to the user to figure out the workflow for getting the SAS labels in to the proper configuration format.

**Comment by agstn** [comment]
If you are importing the dataset from SAS and it contains variables labels, why not just display them? Or does the codebook only works with CSV files in which case the variables labels are not included in the metadata

**Comment by jwildfire** [comment]
The chart uses [json data](https://github.com/RhoInc/web-codebook/wiki/Data-Guidelines), so no metadata is typically included by default.

**Comment by jwildfire** [comment]
I think we can go ahead and add a `config.labels` option in v1.1. We'll leave it to the user to figure out how to populate the object. 

`config.labels` should follow our standard labeling conventions used elsewhere: 

```
config = {
  labels = [ 
    {col_name:"SEX", "label" = "Sex"},
    {col_name:"USUBJID,"label"="Subject ID"}
 ]
}
```

**Comment by jwildfire** [comment]
- The label should be tracked in the settings object as well as in codebook.data.summary_data. 
- when a label is changed on the settings page, it should be updated in both locations.

**Comment by samussiah** [comment]
On it.

**Comment by brittsikora** [comment]
Expected outcome: When the following settings are entered, the user will see new labels associated with the variable names

{"variableLabels": [{"value_col": "USUBJID","label": "Subject ID"}]}


Result: Pass

![98](https://user-images.githubusercontent.com/14914918/27450454-c0fd02b4-5759-11e7-8b61-6d55c02fbff9.JPG)
