### ISSUE TITLE
Update Boxplot colors and add marks for outliers

### ISSUE THREAD

**Issue by agstn** [RhoInc/web-codebook#95]
Boxplots issues:
- The color in the boxplots should be avoided as it doesn't add anything
- I suggest using the original boxplot where the whisker should extend to 1.5 IQR (instead of the maximum and minimum) and outliers plotted as points (see figure below). This will help the viewer diagnose outliers.

![image](https://cloud.githubusercontent.com/assets/6005053/26164117/8a57872e-3ae0-11e7-8f59-3ea28268a615.png)

**Comment by jwildfire** [comment]
Agree with this. Simplifying the box plot colors and adding marks for outliers is a good idea.

**Comment by jwildfire** [comment]
Formatting is an easy fix. Adding points for the outliers is a bit more work, but shouldn't be bad. Adding to v1.1.

**Comment by emmorris** [comment]
Two tasks: 
1. Make the boxplot black and white (no color)
2. Add outliers

All other functionality is working as desired.

**Comment by brittsikora** [comment]
Expected outcome: box plots will be rendered in grayscale and the plots will include ticks for outliers

Result: Pass

![95](https://user-images.githubusercontent.com/14914918/27449212-8ea54f50-5755-11e7-99bb-477be019190f.JPG)
