### ISSUE TITLE
Revise process for Histogram binning

### ISSUE THREAD

**Issue by agstn** [RhoInc/web-codebook#96]
I will argue that the current histogram is not very informative, very few categories and difficult to see the extremes where often the outliers are found.

This is the style I used for my R codebook:

![fireshot capture 62 - - file____s__rhofed_icac_studies_icata_data_derive_cbk_outper pdf](https://cloud.githubusercontent.com/assets/6005053/26164868/ded6a6e8-3ae2-11e7-81ba-fb8e21441a71.png)

Maybe something along these lines may be more useful [dot plot in d3](https://bl.ocks.org/gcalmettes/95e3553da26ec90fd0a2890a678f3f69):

![fireshot capture 63 - live updating dot plot in d3 - bl ocks_ - https___bl ocks org_gcalmettes_95e](https://cloud.githubusercontent.com/assets/6005053/26164947/2d3ce6c6-3ae3-11e7-8236-fbf59960f1f6.png)

**Comment by jwildfire** [comment]
The number of categories is currently automated (see #17). Moving to dots is possible, but might cause performance issues with very large data sets. We're already thinking of limiting the number of levels displayed in the bar charts for very large categorical variables in #50. 

I do like the dot plot though ... could it out  for smaller data sets with less than a few hundred observations ...

**Comment by jwildfire** [comment]
Updated the binning algorithm a few releases ago. Closing this.
