### ISSUE TITLE
Highlight marks when clicked

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#97]
Add the ability to click on a bar (or dot) to open a detailed listing of that subset of data records.

**Comment by jwildfire** [comment]
This is a fairly complex change, but I think it's worth doing. Inclined to hit the low-hanging fruit in v1.1.0 first, and this do this, so going to put this by itself in v1.2 for now.
 
It might be worth thinking about it in conjunction with #59 since both likely involve a new "highlighted" data layer.

**Comment by emmorris** [comment]
Might need to make a highlighted data object for this.  

Disable filters in some way.

Need to figure out how to allow highlighting.  Sliders?  Mock-up and discuss as a team.
High priority because DMEDS folks mentioned this being a solution for issues they are having.

**Comment by jwildfire** [comment]
__Technical Specs__
When a mark is clicked do the following:
1. Give the mark the 'highlighed' class. (Clear the highlighed class from all other marks.)
2. Assign the mark's raw data to codebook.data.highlighted. (Overwrite existing data if any)
3. Show a "clear highlights" button to the controls followed by a note defining the current highlighed population ("[X] records with [Variable X] values of [X to Y] highlighted"). When clicked the button should trigger a 'clearHighlights' method that does the following:
   - clear codebook.data.highlighted
   - clear the highlighed class from amrks
   - delete the note and the button 
   - clear highlights whenever the group control or a filter change

Consider implementing with the following new methods: 
1. `codebook.controls.highlight.init(codebook)` – creates hidden “clear highlight” button and a null codebook.data.highlight object 
2. `codebook.controls.highlight.update(codebook)` – initializes highlights. expects a non-null codebook.data.highlight object.
3. `codebook.controls.highlight.clear(codebook)` – Clears highlights
4. `chart.{chartType}.highlight()` - assigns the 'highlighted' class to a mark and calls `codebook.controls.highlight.update()`. Triggered via new event listeners initialized in the `onResize()` for each of the individual charts.

**Comment by jwildfire** [comment]
Test Notes: Combined test notes for #97, #59 and #142.

Clicking a bar in the codebook bar chart should trigger the following: 
- The number of highlighted records should be noted in the controls title next to the number of rows selected. 
- The bar should become orange indicating that it is selected.
- Orange bars corresponding to data in the selected bar should be drawn in all other bar charts. So, if a large bar is selected, more data will be highlighted in the other charts. 
- The rows for the highlighted records should have an orange background in the data listing view, and they should be shown first in the listing
- Sorting the data listing should work as expected (rows should still be orange, but won't neccesarily be first) 
- Clicking a second bar should override the original selection and change the highlighted data
- Clicking the "Clear Highlighting" button should remove all highlight functionality. 
- Filtering the data, selecting a grouping variable or changing a setting on the settings page should   reset the highlight

The functionality described above should work for all bar chart types, with and without group by variables selected. Test by clicking bars from all of the following: 
- Histogram, grouped
- Histogram, ungrouped
- Vertical bar chart, grouped
- Vertical bar chart, ungrouped
- Horizontal bar chart, grouped
- Horizontal bar chart, ungrouped

**Comment by brittsikora** [comment]
Pass

![97a](https://user-images.githubusercontent.com/14914918/28846438-6e2dd302-76d9-11e7-93a6-d78ae712ba05.JPG)

![97d](https://user-images.githubusercontent.com/14914918/28846497-b01f5ef2-76d9-11e7-893f-cbcf5e5a2bd1.JPG)

![97e](https://user-images.githubusercontent.com/14914918/28846499-b24526d0-76d9-11e7-86b9-e8f5ee77ab80.JPG)

![97f](https://user-images.githubusercontent.com/14914918/28846502-b41a1c90-76d9-11e7-8ca6-96d7125418ab.JPG)
